version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: profissional
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345

    ports:
      - "3306:3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    networks:
      - mysql-compose-network
    restart: always

networks: 
  mysql-compose-network:
    driver: bridge